### ISSUE TITLE
Initial plugin design

### ISSUE THREAD

**Issue by simonw** [simonw/datasette-cookies-for-magic-parameters#1]
Goal is to allow this kind of canned query:
```yml
databases:
  mydatabase:
    queries:
      api_query:
        sql: select 'Your API key is' || :_cookie_openai_api_token;
```
To offer a UI that allows users to set a cookie for that value.

This is to support transmitting things like API keys (for use with https://github.com/simonw/datasette-openai) without risk of logging them in GET query strings.
